version: "3.8"

services:
  backend:
    build: .
    ports:
      - 8080:8080
    environment:
      MONGOURI: mongodb://database/poster
      RUST_LOG: actix
  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - poster:/data/db

volumes:
  poster: